# Generated by Django 5.0.7 on 2025-08-21 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('college', models.CharField(max_length=64, verbose_name='学院')),
                ('class_name', models.CharField(max_length=64, verbose_name='班级')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='O', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
