# Generated by Django 5.0.7 on 2025-08-21 11:50

import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('category', models.CharField(choices=[('lost', '寻物'), ('found', '招领')], default='lost', max_length=10, verbose_name='类型')),
                ('location', models.CharField(max_length=120, verbose_name='地点')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.item_image_path, verbose_name='图片')),
                ('status', models.CharField(choices=[('open', '未解决'), ('resolved', '已归还/已找到')], default='open', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='items.item')),
            ],
        ),
    ]
